name: Search new OCP V releases
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install skopeo
      run: sudo apt-get install skopeo
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Publish tekton images and generate release manifests
      env:
        GH_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        USERNAME: ${{ secrets.USERNAME }}
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      shell: bash
      run: |
        skopeo login -u "${{ secrets.REGISTRY_USERNAME }}" -p "${{ secrets.REGISTRY_PASSWORD }}" registry.redhat.io
        ./check-for-new-release.sh
